name: CI

on:
  pull_request:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.env.example'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync
        working-directory: .

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pytest
        run: uv run pytest --override-ini="addopts=-n auto"
        env:
          TELEGRAM_BOT_KEY: ${{ secrets.TELEGRAM_BOT_KEY }}
          TODOIST_KEY: ${{ secrets.TODOIST_KEY }}
          ANTHROPIC_KEY: ${{ secrets.ANTHROPIC_KEY }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
